#!/usr/bin/env bash
# runarchainWH - To check for an input file to AR-CHAINWH, also
# to printout a timing file time.out .
#
# 20250515 weg, updated, started in 2020.

if [ "$1" = "" ]; then
  echo "ONEUsage: runarchain <input file>"
  echo "Input file must exist."
  exit
fi


if [ ! -f $1 ]; then
  echo "TWOUsage: runarchain <input file>"
  echo "Input file must exist."
  exit
fi

# The shell script path location...
#SCRIPT_DIR=$( cd -- "$( dirname -- "$BASH_SOURCE[0]" )" &> /dev/null && pwd )
#SCRIPT_DIR="$( dirname -- "$BASH_SOURCE[0]" )"
#echo "runarchainWH: SCRIPT_DIR is $SCRIPT_NAME ."

#export PATH=${PATH}:${HOME}/Documents/astro/wormholes/archain/ARChain
export PATH=${PATH}:${HOME}/Documents/astro/wormholes/mikkola/GWToolsWormholes/code/ARChain
#export PATH=${PATH}:$SCRIPT_DIR

# Shell script to run a AR-CHAIN.f input file and to log the start
# and stop times in time.out, as well as save the stdout too.
# started 20190917 gabella

timefile="time.out"
prog="AR-CHAINWH"

# echo "" >> time.out ; date >> time.out; AR-CHAIN < test3bodies.in |tee test3bodies.stdout; date >> time.out

echo "runarchainWH: Using input file $1."
infile=$(basename "$1")
rootname="${infile%.*}"
extension="${infile##*.}"
#echo "rootname $rootname extension $extension"

if true
then
  echo "" >> $timefile
  echo "$1" >> $timefile
  date >> $timefile
  $prog < $1 |tee $rootname.stdout
  date >> $timefile
fi
